env:
  browser: true
  es2023: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parserOptions:
  ecmaVersion: 14
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
